# Default values for kube-xcpng-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
    repository: arturoguerra/xcpng-csi
    tag: v1.1.2

config:
    XCPNG_HOST: "Hostname / IP Address of XCP-NG Server"
    XCPNG_USERNAME: "Username of server"
    XCPNG_ZONE: "XCPNG Server identifier probably use the hostname/server name"

# secretName: "Existing secret Name"
# serviceAccount: "Account Name"
