apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "controller" . }}
  namespace: {{ template "namespace" . }}
  annotations:
    timestamp: {{ template "timestamp" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "controller" . }}
  template:
    metadata:
      labels:
        app: {{ template "controller" . }}
    spec:
      serviceAccount: {{ template "serviceAccount" .}}
      containers:
        # Liveness-probe
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/xcpng.socket
          volumeMounts:
            - name: socket
              mountPath: /var/lib/csi/sockets/pluginproxy
        # CSI Provisioner
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.5.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--enable-leader-election"
            - "--feature-gates=Topology=true"
            - "--strict-topology"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/xcpng.socket
          volumeMounts:
            - name: socket
              mountPath: /var/lib/csi/sockets/pluginproxy
        # CSI Attacher
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v2.1.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/xcpng.socket
          volumeMounts:
            - name: socket
              mountPath: /var/lib/csi/sockets/pluginproxy
        # Controller
        - name: controller
          image: {{ template "image" . }}
          ports:
            - name: healthz
              protocol: TCP
              containerPort: 9808
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: /var/lib/csi/sockets/pluginproxy/xcpng.socket
            - name: CSI_MODE
              value: controller
          envFrom:
            - configMapRef:
                name: {{ template "name" . }}
          volumeMounts:
            - name: socket
              mountPath: /var/lib/csi/sockets/pluginproxy
            - name: config
              mountPath: /config
      volumes:
        - name: socket
          emptyDir: {}
        - name: config
          configMap:
            name: {{ template "name" .}}
            items:
              - key: xcpng-csi.conf
                path: xcpng-csi.conf